# Generated by Django 5.1.6 on 2025-02-27 00:10

import datetime
import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=10, unique=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=350)),
                ('term', models.DateField()),
                ('created_At', models.DateField(default=datetime.datetime(2025, 2, 26, 21, 10, 41, 953398))),
                ('updated_At', models.DateField(max_length=datetime.datetime(2025, 2, 26, 21, 10, 41, 953454))),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('ORC', 'Orçamento e aprovação'), ('COR', 'Corte de materiais'), ('LIX', 'Lixamento e preparação'), ('MON', 'Montagem estrutural'), ('PNT', 'Acabamento e pintura'), ('SEC', 'Secagem e ajustes finais'), ('REV', 'Revisão e controle de qualidade'), ('ENT', 'Pronto para retirada/entrega')], default='ORC', max_length=3)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to=orders.models.upload_path)),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
