# Generated by Django 5.1.6 on 2025-02-27 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_At',
            field=models.DateField(default=datetime.datetime(2025, 2, 27, 0, 14, 7, 324286)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_At',
            field=models.DateField(max_length=datetime.datetime(2025, 2, 27, 0, 14, 7, 324286)),
        ),
    ]
