# Generated by Django 5.1.6 on 2025-02-27 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_created_at_alter_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_At',
            field=models.DateField(default=datetime.datetime(2025, 2, 27, 2, 40, 17, 31381)),
        ),
        migrations.AlterField(
            model_name='order',
            name='term',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_At',
            field=models.DateField(max_length=datetime.datetime(2025, 2, 27, 2, 40, 17, 31381)),
        ),
    ]
