# Generated by Django 5.1.6 on 2025-02-27 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_created_at_alter_order_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_At',
            field=models.DateField(default=datetime.datetime(2025, 2, 27, 2, 42, 38, 853502)),
        ),
        migrations.AlterField(
            model_name='order',
            name='term',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_At',
            field=models.DateField(max_length=datetime.datetime(2025, 2, 27, 2, 42, 38, 853502)),
        ),
    ]
