# Generated by Django 5.1.6 on 2025-02-27 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_created_at_alter_order_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_At',
            field=models.DateField(default=datetime.date(2025, 2, 27)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_At',
            field=models.DateField(default=datetime.date(2025, 2, 27), max_length=datetime.date(2025, 2, 27)),
        ),
    ]
