# Generated by Django 5.1.6 on 2025-02-28 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_created_at_alter_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_At',
            field=models.DateField(default=datetime.date(2025, 2, 28)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_At',
            field=models.DateField(default=datetime.date(2025, 2, 28), max_length=datetime.date(2025, 2, 28)),
        ),
    ]
